config/routes.rb
Rails.application.routes.draw do
  resources :books
  
  resources :users, only: [:show, :new, :create]
  
  resources :transactions, only: [:new, :create]

  resources :authors, only: [:show]
  
  resources :genres, only: [:show]

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  post "/logout", to: "sessions#destroy"
  
  get "/tasks", to: "users#tasks"

  post "/accept", to: "transactions#accept"
  post "/decline", to: "transactions#decline"
  
  get "/home", to: "application#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    belongs_to :genre
    belongs_to :author
    has_many :transactions
    
    validates :title, presence: true
    validates :description, presence: true
    
    def genre_name
        self.genre.name
    end
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :books
end

app/models/transaction.rb
class Transaction < ApplicationRecord
    belongs_to :sender, :class_name => "User", :foreign_key => "sender_id"
    belongs_to :receiver, :class_name => "User", :foreign_key => "receiver_id"
    belongs_to :book

    def book
        Book.find(self.book_id)
    end

    def book_title
        book.title
    end

    def book_author
        book.author.name
    end

    def receiver_name
        User.find(self.receiver_id).name
    end

    def sender_name
        User.find(self.sender_id).name
    end 
end

app/models/user.rb
class User < ApplicationRecord
    has_many :books
    has_many :sent_transactions, :class_name => "Transaction", :foreign_key => "sender_id"
    has_many :received_transactions, :class_name => "Transaction", :foreign_key => "receiver_id"
    
    validates :name, presence: true, uniqueness: true
    
    has_secure_password
    
    def self.most_active
	    most_active_user = nil
	    num_transactions = 0
	    
	    self.all.each do |user|
		    if user.total_transactions > num_transactions
			    most_active_user = user
			    num_transactions = user.total_transactions
			  end
		  end
		  
		  most_active_user
	  end
	  
	  def total_transactions
		  total_transactions = self.sent_transactions.size + self.received_transactions.size
		end
		
		def self.most_active_name
			self.most_active.name
		end
		
		def self.most_transactions_count
			self.most_active.total_transactions
		end
		
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def logged_in
        if !session[:user_id]
            redirect_to login_path
        end
    end
    
    def home
	    @books = Book.all
	    @users = User.all
	    @genres = Genre.all
	    @authors = Genre.all
	    @transactions = Transaction.all
	  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
    before_action :logged_in
    
    def show
        @author = Author.find(params[:id])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :logged_in
  
    def index
      @books = Book.all
    end
  
    def show
      @book = Book.find(params[:id])
      @transaction = Transaction.new
    end
  
    def new
	    @book = Book.new
	  end
	
	  def create
		  @book = Book.new(book_params)
		  
		  if @book.save
			  redirect_to user_path(session[:user_id])
			else
				redirect_to new_book_path
			end
	  end
	  
	  def edit
			@book = Book.find(params[:id])
		end
		
		def update
			@book = Book.find(params[:id])
			if @book.update(book_params)
				redirect_to user_path(@book.user_id)
			else
				redirect_to edit_book_path(@book.id)
			end
		end
		
		def destroy
			Book.destroy(params[:id])
			
			redirect_to user_path(session[:user_id])
		end	
		
	  
	  private
	  
	  def get_book
			@book = Book.find(params[:id])
		end
	  
	  def book_params
		  params.require(:book).permit(:title, :description, :author_id, :genre_id, :user_id)
		end
   
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
    before_action :logged_in
    
    def show
        @genre = Genre.find(params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
	def new
		
	end
	
	def create
		@user = User.find_by(name: params[:name])
		# byebug
		if @user && @user.authenticate(params[:password])
			session[:user_id] = @user.id
			
			#flash[:message] = "Welcome #{@user.name}"
			redirect_to books_path
		else
			redirect_to login_path
		end
	end

	def destroy
		session.delete :user_id
				
		redirect_to home_path
	end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
	before_action :logged_in
	
	def new
		#@transaction = Transaction.new
	end
	
	def create
		# byebug
		#add column for status, add sender_id
		@transaction = Transaction.create(transaction_params)
		redirect_to tasks_path
	end
	
	def accept
		@transaction = Transaction.find(params[:transaction][:received_transaction_id])
		@book = Book.find(@transaction.book_id)
		@book.user_id = @transaction.sender_id
		@book.save
		# byebug
		@transaction.open = 0
		@transaction.save
		redirect_to tasks_path
	end

	def decline
		@transaction = Transaction.find(params[:transaction][:received_transaction_id])
		@transaction.open = 0
		@transaction.save
		redirect_to tasks_path
	end

	private
	
	def transaction_params
		#later on add sender_id from session data
		params.require(:transaction).permit(:book_id, :receiver_id, :sender_id, :open)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :logged_in, only: [:show, :tasks]
	
	def show
		@user = User.find(params[:id])
	end
	
	def new
		@user = User.new
	end
	
	def create
		@user = User.new(user_params)
		
		if @user.save && user_params[:password] == user_params[:password_confirmation]
			session[:user_id] = @user.id
			
			redirect_to books_path
		else
			redirect_to new_user_path
		end
	end
	
	def tasks
		@user = User.find(session[:user_id])
	end

	# Create a new action, route, view for user's library?
	
	private
	
	def user_params
		params.require(:user).permit(:name, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Book Grabber</title>
    </head>
    <body>
        <h1>Book Grabber</h1>
        <%= yield %>
    </body>
</html>

app/views/application/home.html.erb
<div class="welcome">
    <h1>Welcome to Book Grabber</h1>
    <p>Looking for a book? Find it right here.</p>
    
    <div>
        <% if session[:user_id] == nil %>
            <h4>Get Started</h4>
            <div>
                <a href="<%= new_user_path %>"><button type="button" class="btn btn-primary">Sign Up</button></a>
                <a href="<%= login_path %>"><button type="button" class="btn btn-primary">Login</button></a> 
            </div>
        <% end %>
    </div>
</div>
    
<div class="stats">
    <p class="sub-header">Book Grabber Service Statistics</p>
    <p>Book Trader currently has <%= @users.size %> users and <%= @books.size %> books in circulation.</p>
    <p>Books span <%= @genres.size %> genres from <%= @authors.size %> authors.</p>
    <p>Our users have made <%= @transactions.size%> transactions.</p>
    <p>The most active trader is <%= User.most_active_name %> with <%= User.most_transactions_count %> transactions. </p>
</div>

app/views/authors/show.html.erb
<h3>Books by<br><%= @author.name %></h1>
<table class="table">
    <thead>
        <tr>
            <th>Title</th>
            <th>Genre</th>
        </tr>
    </thead>
    <tbody>
        <% @author.books.each do |book| %>
            <tr>
                <td><%= link_to book.title, book %></td>
                <td><%= link_to book.genre_name, book.genre %>
            </tr>
        <% end %> 
    </tbody>
</table>   

app/views/books/edit.html.erb
<h3>Edit Book</h3>
<div class="form-container">
	<%= form_for @book do |f| %>
		<div class="form-group">
			<%= f.label :title %>
			<%= f.text_field :title, class: "form-control" %>
		</div>
		<div class="form-group">
			<%= f.label "Short Description" %>
			<%= f.text_area :description, class: "form-control" %>
		</div>
		<div class="form-group">
			<%= f.label "Author" %>
			<div class="input-group">
				<%= f.collection_select :author_id, Author.all, :id, :name %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label "Genre" %>
			<div class="input-group">
				<%= f.collection_select :genre_id, Genre.all, :id, :name %>
			</div>
		</div>
			<%= f.hidden_field :user_id, value: session[:user_id] %><br>
		<div class="form-group">
			<%= f.submit "Submit Changes", class: "btn btn-primary" %>
		</div>
	<% end %>
		<%= form_for @book, method: :DELETE do |f| %>
		<%= f.submit "Remove From Library", class: "btn btn-warning"  %>
	<% end %>
</div>

app/views/books/index.html.erb
<h3>Browse All Books</h3>
<table class="table">
<thead>
    <tr>
    <th scope="col">Title</th>
    <th scope="col">Author</th>
    </tr>
<tbody>
    <% @books.each do |book| %>
        <tr>
        <td><%= link_to book.title, book %></td>
        <td><%= link_to book.author.name, book.author %></td>
        </tr>
    <% end %>
</tbody>
</table>

app/views/books/new.html.erb
<h3>Add a Book To Your Library</h3>
<div class="form-container">
	<%= form_for @book do |f| %>
		<div class="form-group">
			<%= f.label :title %>
			<%= f.text_field :title, class: "form-control" %><br>
		</div>
		<div class="form-group">
			<%= f.label "Short Description" %>
			<%= f.text_area :description, class: "form-control" %><br>
		</div>
		<div class="form-group">
			<%= f.label "Author" %>
			<div class="input-group">
				<%= f.collection_select :author_id, Author.all, :id, :name, class: "form-control" %><br>
			</div>
		</div>
		<div class="form-group">
			<%= f.label "Genre" %>
			<div class="input-group">
				<%= f.collection_select :genre_id, Genre.all, :id, :name, class: "form-control" %><br>
			</div>
		</div>
			<%= f.hidden_field :user_id, value: session[:user_id] %><br>
		<div class="form-group">
			<%= f.submit "Submit", class: "btn btn-primary" %>
		</div>
		
	<% end %>
</div>

app/views/books/show.html.erb
<div class="table-container">
	<h3><%= @book.title %></h3>
	<table class="table">
		<tr>
			<th>Author:</th>
			<td><%= link_to @book.author.name, author_path(@book.author) %></td>
		<tr>
		<tr>
			<th>Genre:</th>
			<td><%= link_to @book.genre_name, genre_path(@book.genre) %></td>
		<tr>
		<tr>
			<th>Description</th>
			<td><%= @book.description %></td>
		<tr>
		<tr>
			<th>Current Holder:</th>
			<td><%= link_to @book.user.name, user_path(@book.user) %></td>
		<tr>
	</table>
	<% records = Transaction.all.select do |transaction| %>
		<% transaction.book_id == @book.id && transaction.open == 1 %>
	<% end %>
	
	<% if records.count == 0 && @book.user_id != session[:user_id] %>
		<%= form_for @transaction do |f| %>
			<%= f.hidden_field :book_id, value: @book.id %>
			<%= f.hidden_field :receiver_id, value: @book.user_id %>
			<%= f.hidden_field :sender_id, value: session[:user_id] %>
			<%= f.hidden_field :open, value: 1 %>
			<button type="submit" class="btn btn-success">Request Book</button>
		<% end %>
	<% end %>

	<% if session[:user_id] == @book.user_id %>
		<%= form_for @book, url: edit_book_path, method: :GET do |f| %>
			<button type="submit" class="btn btn-warning">Edit/Delete Book</button>		
		<% end %>
	<% end %>
</div>

app/views/genres/show.html.erb
<h3><%= @genre.name %> Books</h3>
<table class="table">
    <thead>
        <tr>
            <th>Title</th>
            <th>Author</th>
        </tr>
    </thead>
    <tbody>
        <% @genre.books.each do |book| %>
        <tr>
            <td><%= link_to book.title, book %></td>
            <td><%= link_to book.author.name, book.author %></td>
            <%# add author_name to book model %>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book Grabber</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Raleway:300,400,700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-expand-lg navbar-light">
  <a class="navbar-brand" style="padding-bottom: 0.33em" href="/home">Book Grabber</a>
    <div class="navbar-nav">
<!-- 	    redundant home link -->
<!--       <a class="nav-item nav-link active" href="/home">Home <span class="sr-only">(current)</span></a> -->
      <% if session[:user_id] != nil %>
        <a class="nav-item nav-link" href="/books">Browse Books</a>
        <a class="nav-item nav-link" href="<%= user_path(session[:user_id])%>">My Library</a>
        <a class="nav-item nav-link" href="/tasks">My Tasks</a>
        <%= link_to "Logout", logout_path, method: :post, class: "nav-item nav-link" %>
      <% else %>
        <a class="nav-item nav-link" href="/login">Login</a>
        <a class="nav-item nav-link" href="/users/new">Signup</a>
      <% end %>
    </div>
</nav>
   <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<div class="signup">
	<h3>New User Signup</h3>
		<%= form_for @user do |f| %>
			<div class="form-group">
				<%= f.label :name %>
				<%= f.text_field :name, class: "form-control" %><br>
			</div>
			<div class="form-group">
				<%= f.label :password %>
				<%= f.password_field :password, class: "form-control" %><br>
			</div>
			<div class="form-group">
				<%= f.label :password_confirmation %>
				<%= f.password_field :password_confirmation, class: "form-control" %><br>
			</div>
			<div class="form-group">
				<%= f.submit "Sign Up", class: "btn btn-primary" %>
			</div>
		<% end %>
</div>

app/views/users/show.html.erb
<h3><%= @user.name %>'s Library</h3>
<table class="table">
	<thead>
		<tr>
			<th>Title</th>
			<th>Author</th>
		</tr>
	</thead>
	<tbody>
		<% @user.books.each do |book| %>
			<tr>
				<td><%= link_to book.title, book_path(book) %></td>
				<td><%= link_to book.author.name, author_path(book.author_id) %>
			</tr>
		<% end %> 
	</tbody>
</table>

<% if session[:user_id] == @user.id %>
	<a href="<%= new_book_path %>"><button type="button" class="btn btn-primary">Add a Book</button></a>
<% end %>

app/views/users/tasks.html.erb
<h3><%= @user.name %>'s Tasks</h3>
<br>
<div>
	<div>
			<h4>Open Transactions</h4><br>
			<div>
		    <p class="sub-header">Your requests:</p>
        <% open_transactions = @user.sent_transactions.select do |t| %>
            <% t.open == 1%>
        <% end %>
        <% if open_transactions.count == 0 %>
            <span>(No requests pending)</span>
        <% else %>
        	<div class="tasks-list">
            <ol class="tasks-item">
                <% open_transactions.each do |t| %>
                    <li style="text-align: left;"><%= link_to t.book_title, book_path(t.book) %> by <%= t.book_author %><br>
                    held by <%= t.receiver_name %></li>
                <% end %>
            </ol>
          </div>
        <% end %>
			</div>
		
		<br>
		
		<div>
		    <p class="sub-header">Received requests:</p>
		    <% open_transactions = @user.received_transactions.select do |t| %>
		        <% t.open == 1 %>
		    <% end %>
		    <% if open_transactions.count == 0 %>
		        <span>(No requests pending)</span>
		    <% else %>
		    	<div class="tasks-list">
		        <ol class="tasks-item">
		            <% open_transactions.each do |t| %>
		                <li style="text-align: left;"><%= link_to t.book_title, book_path(t.book) %> by <%= t.book_author %><br>
		                by <%= t.sender_name %></li>
		                <div>
			                <div style="display: inline-block;">
				                <%= form_for t, url: accept_path, method: :post do |f| %>
			                    <%= f.hidden_field :received_transaction_id, value: t.id %>
			                    <%= f.submit "Accept", class: "btn btn-primary" %>
												<% end %>
			                </div>
			                <div style="display: inline-block;">
				                <%= form_for t, url: decline_path, method: :post do |f| %>
			                    <%= f.hidden_field :received_transaction_id, value: t.id %>
			                    <%= f.submit "Decline", class: "btn btn-secondary" %>
												<% end %>
											</div>
		                </div>
		            <% end %>
		        </ol>
		      </div>
		    <% end %>
		</div>
	</div>
	
	<br><br>
	
	<div>
	    <h4>Closed Transactions</h4><br>
	    <div>
	        <p class="sub-header">Requests made:</p>
	            <% closed_transactions = @user.sent_transactions.select do |t| %>
	                <% t.open == 0%>
	            <% end %>
	            <% if closed_transactions.count == 0 %>
	                <span>You've never requested a book!</span>
	            <% else %>
	            	<div class="tasks-list">
	                <ol class="tasks-item">
	                    <% closed_transactions.each do |t| %>
	                        <li style="text-align: left;"><%= link_to t.book_title, book_path(t.book) %> by <%= t.book_author %><br>
	                        held by <%= t.receiver_name %></li>
	                    <% end %>
	                </ol>
	              </div>
	            <% end %>
	    </div>
	    
	    <br>
	    
	    <div>
	        <p class="sub-header">Requests received:</p>
	        <% closed_transactions = @user.received_transactions.select do |t| %>
	            <% t.open == 0%>
	        <% end %>
	        <% if closed_transactions.count == 0 %>
	            <span>You haven't received a book request yet!</span>
	        <% else %>
	        	<div class="tasks-list">
	            <ol class="tasks-item">
	                <% closed_transactions.each do |t| %>
	                    <li style="text-align: left;"><%= link_to t.book_title, book_path(t.book) %> by <%= t.book_author %><br>
	                    held by <%= t.receiver_name %></li>
	                <% end %>
	            </ol>
	          </div>
	        <% end %>
	    </div>
	</div>
</div>